BlogApp/Controllers/AutorController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Models;
using Services.Interface;
using Microsoft.AspNetCore.Authorization;

namespace BlogApp.Controllers
{
    [Authorize]
    [Route("autor")]
    public class AutorController : Controller
    {
        private readonly IAutorService _service;
        public AutorController(IAutorService service)
        {
            _service = service;
        }

        [Route("index")]
        [HttpGet]
        public IActionResult Index(string mensagem = null)
        {
            ListarAutoresViewModel viewModel = new ListarAutoresViewModel
            {
                Autores = _service.ListarTodos(),
                Mensagem = mensagem
            };

            return View(viewModel);
        }

        [Route("novo")]
        [HttpGet]
        public IActionResult Criar()
        {
            return View();
        }

        [Route("novo")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Criar(AutorViewModel autor)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            _service.Criar(autor);

            return RedirectToAction(nameof(Index), new { mensagem = "Autor criado com sucesso!"});
        }

        [Route("remover")]
        [HttpGet]
        public IActionResult Remover(int id)
        {
            var autor = _service.ProcurarPorIdTrazerPosts(id);
            
            var viewModel = _service.ConverterParaAutorViewModel(autor);

            if ( viewModel == null)
            {
                return RedirectToAction(nameof(Index));
            }
                
            return View(viewModel);
        }

        [Route("remover")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Remover(AutorViewModel autor)
        {
            _service.Remover(autor);

            return RedirectToAction(nameof(Index));
        }

        [Route("editar")]
        [HttpGet]
        public IActionResult Editar(int id)
        {
            AutorViewModel viewModel = new AutorViewModel();
            viewModel = _service.ConverterParaAutorViewModel(_service.ProcurarPorId(id));
            return View(viewModel);
        }

        [Route("editar")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(AutorViewModel viewModel)
        {
            _service.Editar(viewModel);
            return RedirectToAction(nameof(Index));
        }
    }
}

BlogApp/Views/Autor/Editar.cshtml
@{
    @model Services.Models.AutorViewModel;
    Layout = "LayoutPainel";
}

<!-- Main Content -->
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Editar registro</h1>
        <p class="mb-4">
            Altere as informações abaixo para editar o registro.
        </p>

        <!-- Form -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Cadastro</h6>
            </div>
            <div class="card-body">
                <div class="mt-3 col-md-8">
                    @using (Html.BeginForm("editar", "Autor", FormMethod.Post, new { id = "form-editar" }))
                    {
                        <div class="form-group">
                            @Html.EditorFor(x => x.Nome, new { htmlAttributes = new { @class = "form-control", placeholder = Model.Nome } })
                        </div>
                        <div class="form-group">
                            @Html.EditorFor(x => x.Youtube, new { htmlAttributes = new { @class = "form-control", placeholder = Model.Youtube } })
                        </div>
                        <div class="form-group">
                            @Html.EditorFor(x => x.Twitter, new { htmlAttributes = new { @class = "form-control", placeholder = Model.Twitter } })
                        </div>
                        <div class="form-group">
                            @Html.EditorFor(x => x.Linkedin, new { htmlAttributes = new { @class = "form-control", placeholder = Model.Linkedin } })
                        </div>
                        <div class="form-group">
                            @Html.EditorFor(x => x.Github, new { htmlAttributes = new { @class = "form-control", placeholder = Model.Github } })
                        </div>
                        <div class="form-group">
                            @Html.TextAreaFor(x => x.Biografia, new { htmlAttributes = new { @class = "form-control", placeholder = Model.Biografia } })
                        </div>
                        <div>
                            @Html.HiddenFor(x => x.DataCriacao, new {htmlAttributes = new{ value="@Model.DataCriacao"}})
                        </div>
                        <div>
                            @Html.HiddenFor(x => x.Id)
                        </div>
                        <button type="submit" class="btn btn-info">Salvar</button>
                    }
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->
<!-- End of Content Wrapper -->

@section Scripts {
    <script src="~/painel/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace('Biografia');
    </script>
    <script>
        $(document).ready(function () {
            $('#postsTable').DataTable();
        });
    </script>
}

BlogApp/Views/Autor/Index.cshtml
@{
    @model Services.Models.ListarAutoresViewModel;
    Layout = "LayoutPainel";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <a asp-action="novo" asp-controller="autor"><button class="btn btn-info mb-3">Novo</button></a>
    @if(Model.Mensagem != null)
    {
        <div class="alert alert-success" role="alert">
            @Model.Mensagem
        </div>
    }
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Autores</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Data</th>
                            <th>Editar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var a in Model.Autores)
                        {
                            <tr>
                                <td>@a.Id</td>
                                <td>@a.Nome</td>
                                <td>@a.DataCriacao</td>
                                <td>
                                    <a asp-action="remover" asp-controller="autor" asp-route-id="@a.Id"><button class="btn btn-danger mb-3">Excluir</button></a>
                                    <a asp-action="editar" asp-controller="autor" asp-route-id="@a.Id"><button class="btn btn-info mb-3">Editar</button></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
<!-- End of Main Content -->
@section Scripts
{
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable();
        });
    </script>
}

BlogApp/Views/Autor/Remover.cshtml
@{
    @model Services.Models.AutorViewModel;
    Layout = "LayoutPainel";
}


<!-- Main Content -->
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Deletar</h1>
        <p class="mb-4">
            As informações abaixo serão excluídas do sistema, juntamente com os posts vinculados a esse Autor.
        </p>

        <!-- Form -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Cadastro</h6>
            </div>
            <div class="card-body">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Principal</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#perfil" role="tab" aria-controls="profile" aria-selected="false">Posts</a>
                    </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="mt-3 col-md-8">
                            @using (Html.BeginForm("remover", "Autor", FormMethod.Post, new { id = "form-remove" }))
                            {
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="@Model.Nome" readonly>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="@Model.Youtube" readonly>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="@Model.Twitter" readonly>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="@Model.Github" readonly>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="@Model.Linkedin" readonly>
                                </div>
                                <div class="form-group">
                                    <textarea name="Biografia" id="Biografia" class="form-control">@Model.Biografia</textarea>
                                </div>
                                <div>
                                    <input type="hidden" name="id" value="@Model.Id" readonly>
                                </div>
                                <button type="submit" class="btn btn-info">Excluir</button>
                            }           
                        </div>
                    </div>
                    <div class="tab-pane fade" id="perfil" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="table-responsive">
                            <div class="mt-3 col-md-6">
                                <table class="table" id="postsTable">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Titulo</th>
                                            <th>Data</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var post in Model.Posts)
                                        {
                                            <tr>
                                                <td>@post.Id</td>
                                                <td>@post.Titulo</td>
                                                <td>@post.DataCriacao</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->
<!-- End of Content Wrapper -->

@section Scripts {
    <script src="~/painel/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace('Biografia');
    </script>
    <script>
        $(document).ready(function () {
            $('#postsTable').DataTable();
        });
    </script>
}