BlogApp/Controllers/SobreController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Interface;
using Services.Models;
using Microsoft.AspNetCore.Authorization;

namespace BlogApp.Controllers
{
    [Authorize]
    [Route("sobre")]
    public class SobreController : Controller
    {
        private readonly ISobreService _service;
        public SobreController(ISobreService service)
        {
            _service = service;
        }
        [Route("index")]
        [HttpGet]
        public IActionResult Index()
        {
            return View(_service.ListarTodos());
        }

        [Route("novo")]
        [HttpGet]
        public IActionResult Criar()
        {
            return View();
        }

        [Route("novo")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Criar(SobreViewModel viewModel)
        {
            _service.Criar(viewModel);
            return RedirectToAction(nameof(Index));
        }

        [Route("remover")]
        [HttpGet]
        public IActionResult Remover(int id)
        {
            if (_service.ProcurarPorId(id) == null)
                return RedirectToAction(nameof(Index));
            return View(_service.ProcurarPorId(id));
        }

        [Route("remover")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Remover(SobreViewModel viewModel)
        {
            _service.Remover(viewModel);
            return RedirectToAction(nameof(Index));
        }

        [Route("editar")]
        [HttpGet]
        public IActionResult Editar(int id)
        {
            return View(_service.ProcurarPorId(id));
        }

        [Route("editar")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(SobreViewModel viewModel)
        {
            _service.Editar(viewModel);
            return RedirectToAction(nameof(Index));
        }
    }
}

BlogApp/Views/Sobre/Criar.cshtml
@{
    @model Services.Models.SobreViewModel;
    Layout = "LayoutPainel";
}


<!-- Main Content -->
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Sobre</h1>
        <p class="mb-4">
            Preencha as informações abaixo para registrar uma nova Descrição para o blog.
        </p>

        <!-- Form -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Novo cadastro</h6>
            </div>
            <div class="card-body">
                <div class="col-md-8">
                    @using (Html.BeginForm())
                    {
                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(x => x.Descricao)
                            @Html.EditorFor(x => x.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(x => x.Conteudo)
                            @Html.TextAreaFor(x => x.Conteudo, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="mb-3">
                            @Html.CheckBoxFor(x => x.StatusAtivo, new { htmlAttributes = new { @class = "form-check-input" } })
                            @Html.LabelFor(x => x.StatusAtivo, new { htmlAttributes = new { @class = "form-check-label" } })                      
                        </div>
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    }
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->
<!-- End of Content Wrapper -->

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/painel/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace('Conteudo');
    </script>
}

BlogApp/Views/Sobre/Editar.cshtml
@{
    @model Services.Models.SobreViewModel;
    Layout = "LayoutPainel";
}


<!-- Main Content -->
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Sobre</h1>
        <p class="mb-4">
            Use este formulário para alterar a descrição do Blog.
        </p>

        <!-- Form -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Cadastro</h6>
            </div>
            <div class="card-body">
                <div class="col-md-8">
                    @using (Html.BeginForm("editar", "Sobre", FormMethod.Post, new { id = "form-editar" }))
                    {
                        <div class="form-group">
                            @Html.EditorFor(x => x.Descricao, new { htmlAttributes = new { @class = "form-control", placeholder = Model.Descricao } })
                        </div>
                        <div class="form-group">
                            @Html.TextAreaFor(x => x.Conteudo, new { htmlAttributes = new { @class = "form-control", placeholder = Model.Conteudo } })
                        </div>
                        <div class="form-group">
                            @Html.CheckBoxFor(x => x.StatusAtivo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.LabelFor(x => x.StatusAtivo)
                        </div>
                        <div class="form-group">
                            @Html.HiddenFor(x => x.Id)
                        </div>
                        <div class="form-group">
                            @Html.HiddenFor(x => x.DataCriacao)
                        </div>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                    }
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->
<!-- End of Content Wrapper -->

@section Scripts {
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/painel/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    CKEDITOR.replace('Conteudo');
</script>
}

BlogApp/Views/Sobre/Index.cshtml
@{
    @model Services.Models.ListarSobresViewModel;
    Layout = "LayoutPainel";
}

<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- DataTales Example -->
    <a asp-action="novo" asp-controller="sobre"><button class="btn btn-info mb-3">Novo</button></a>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Sobre</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Data</th>
                            <th>Status</th>
                            <th>Editar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var sobre in Model.Sobres)
                        {
                            <tr>
                                <td>@sobre.Id</td>
                                <td>@sobre.Descricao</td>
                                <td>@sobre.DataCriacao</td>
                                @if (sobre.StatusAtivo == 'S')
                                {
                                    <td><span class="badge badge-pill badge-success">Ativo</span></td>
                                }
                                else
                                {
                                    <td><span class="badge badge-pill badge-dark">Desabilitado</span></td>
                                }
                                <td>
                                    @if (sobre.StatusAtivo == 'S')
                                    {
                                        <a asp-action="editar" asp-controller="sobre" asp-route-id="@sobre.Id"><button class="btn btn-info mb-3">Editar</button></a>
                                    }
                                    else
                                    {
                                        <a asp-action="remover" asp-controller="sobre" asp-route-id="@sobre.Id"><button class="btn btn-danger mb-3">Excluir</button></a>
                                        <a asp-action="editar" asp-controller="sobre" asp-route-id="@sobre.Id"><button class="btn btn-info mb-3">Editar</button></a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
<!-- End of Main Content -->
@section Scripts
{
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable();
        });
    </script>
}

BlogApp/Views/Sobre/Remover.cshtml
@{
    @model Services.Models.SobreViewModel;
    Layout = "LayoutPainel";
}


<!-- Main Content -->
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Deletar</h1>
        <p class="mb-4">
            As informações abaixo serão excluídas do sistema.
        </p>

        <!-- Form -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Cadastro</h6>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("remover", "Sobre", FormMethod.Post, new { id = "form-remove" }))
                {
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="@Model.Descricao" readonly>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" id="Conteudo">@Model.Conteudo</textarea>
                    </div>
                    <div class="form-group">
                    </div>
                    <div>
                        <input type="hidden" name="id" value="@Model.Id" readonly>
                    </div>
                    @if (Model.StatusAtivoFormatoChar == 'S')
                    {
                        <div class="alert alert-danger col-md-6" role="alert">
                            Não é possível remover uma descrição Ativa.
                        </div>
                    }
                    else
                    {
                        <button type="submit" class="btn btn-info">Excluir</button>
                    }
                }
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
</div>
<!-- End of Main Content -->
<!-- End of Content Wrapper -->

@section Scripts {
    <script src="~/painel/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace('Conteudo');
    </script>
}