BlogApp/Controllers/BlogController.cs
using Dominio;
using Microsoft.AspNetCore.Mvc;
using Services.Interface;
using Services.Models;
using System.Threading.Tasks;

namespace BlogApp.Controllers
{
    [Route("blog")]
    public class BlogController : Controller
    {
        private readonly ISobreService _sobreService;
        private readonly IPostService _postService;
        public BlogController(ISobreService sobreService, IPostService postService)
        {
            _postService = postService;
            _sobreService = sobreService;
        }
        [Route("index")]
        public IActionResult Index()
        {
            return View(_postService.PostsParaIndex());
        }

        [Route("about")]
        [HttpGet]
        public IActionResult About()
        {
            return View(_sobreService.ProcurarPorStatus('S'));
        }

        [Route("contact")]
        [HttpGet]
        public IActionResult Contact(string message = null)
        {
            var viewModel = new ContatoViewModel{
                Message = message
            };

            return View(viewModel);
        }

        [Route("olders")]
        [HttpGet]
        public async Task<IActionResult> Older(int? pageNumber)
        {
            var posts = _postService.ListarTodosQueryable();
            return View(await ListarPostsViewModelPaginated<Post>.CreateAsync(posts, pageNumber ?? 1, 3));
        }
    }
}

BlogApp/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interface;
using Services.Models;

namespace BlogApp.Controllers
{
    [Authorize]
    public class ContatoController : Controller
    {
        public IContatoService _service { get; set; }
        public ContatoController(IContatoService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [Route("salvarContato")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SalvarContato(ContatoViewModel viewModel)
        {
            if(!ModelState.IsValid)
                return View("../Blog/Contact");

            _service.Salvar(viewModel);
            return RedirectToAction("Contact","Blog", new { message = "Mensagem enviada com sucesso! "});
        }
    }
}

BlogApp/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interface;
using Services.Models;

namespace BlogApp.Controllers
{
    [Authorize]
    [Route("post")]
    public class PostController : Controller
    {
        public IPostService _service;
        public IAutorService _autorService;
        public PostController(IPostService service, IAutorService autorService)
        {
            _service = service;
            _autorService = autorService;
        }
        [Route("index")]
        [HttpGet]
        public IActionResult Index(string message = null)
        {
            ListarPostsViewModel viewModel = new ListarPostsViewModel
            {
                Posts = _service.ListarTodos(),
                Message = message 
            };
            return View(viewModel);
        }

        [Route("novo")]
        [HttpGet]
        public IActionResult Criar()
        {
            PostViewModel viewModel = new PostViewModel
            {
                AutoresDisponiveis = _autorService.ListarTodos()
            };

            return View(viewModel);
        }

        [Route("novo")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Criar(PostViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View();

            _service.Criar(viewModel);

            return RedirectToAction(nameof(Index), new { message = "Registro criado com sucesso!"});
        }

        [AllowAnonymous]
        [Route("visualizar")]
        [HttpGet]
        
        public IActionResult Visualizar(int id)
        {
            return View(_service.Visualizar(id));
        }

        [Route("remover")]
        [HttpGet]
        public IActionResult Remover(int id)
        {
            return View(_service.ConverterPostParaViewModel(_service.ProcurarPorId(id)));
        }

        [Route("remover")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Remover(PostViewModel viewModel)
        {
            _service.Remover(viewModel.Id);
            return RedirectToAction("Index", new { message = "Registro removido com sucesso!"});
        }

        [Route("editar")]
        [HttpGet]
        public IActionResult Editar(int id)
        {
            return View(_service.ConverterPostParaViewModel(_service.ProcurarPorId(id)));
        }

        [Route("editar")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(PostViewModel viewModel)
        {
            _service.Editar(viewModel);
            return RedirectToAction("Index", new { message = "Registro alterado com sucesso!" });
        }
    }
}

BlogApp/Views/Blog/About.cshtml
@{
    @model Services.Models.SobreViewModel;
    Layout = "LayoutBlog";
}

<!-- Page Header-->
<header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                @if(Model != null)
                    @Html.Raw(Model.Conteudo)
            </div>
        </div>
    </div>
</main>

BlogApp/Views/Blog/Contact.cshtml
@{
    @model Services.Models.ContatoViewModel;
    Layout = "LayoutBlog";
}

<!-- Page Header-->
<header class="masthead" style="background-image: url('assets/img/contact-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Blog do Vitor</h1>
                    <span class="subheading">Entre em contato</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Quer entrar em contato? Preencha o formulário abaixo para me enviar uma mensagem e entrarei em contato com você o mais breve possível!</p>
                        <div class="my-5">
                            @if(Model.Message != null)
                            {
                                <div class="alert alert-success" role="alert">
                                    @Model.Message
                                </div>
                            }
                            @Html.ValidationSummary(false,"", new {@class = "text-danger"})
                            <form id="contactForm" asp-action="salvarContato" asp-controller="Contato" method="post">
                                <div class="form-floating">
                                    <input class="form-control" asp-for="@Model.Nome" type="text" placeholder="Digite seu nome..."/>
                                    <label asp-for="@Model.Nome">Nome</label>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" asp-for="@Model.Email" type="email" placeholder="Digite seu email..."/>
                                    <label asp-for="@Model.Email">Email</label>
                                </div>
                                <div class="form-floating">
                                    <textarea class="form-control" asp-for="@Model.Mensagem" placeholder="Digite a mensagem..." style="height: 12rem"></textarea>
                                    <label asp-for="@Model.Mensagem">Mensagem</label>
                                </div>
                                <br />
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Enviar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>

BlogApp/Views/Blog/Index.cshtml
@{
    @model Services.Models.ListarPostsViewModel;
    Layout = "LayoutBlog";
}

<!-- Page Header-->
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            @foreach (var post in Model.Posts)
            {
                <!-- Post preview-->
                <div class="post-preview">
                    <a asp-action="visualizar" asp-controller="Post" asp-route-id="@post.Id">
                        <h2 class="post-title">@post.Titulo</h2>
                        <h3 class="post-subtitle">@post.Subtitulo</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#!">@post.Autor.Nome</a>
                        on @String.Format("{0: dd/MM/yyyy hh:mm}", post.DataCriacao)
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            }
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary text-uppercase" asp-action="olders" asp-controller="Blog">Older Posts →</a>
            </div>
        </div>
    </div>
</div>

BlogApp/Views/Blog/Older.cshtml
@{
    Layout = "LayoutBlog";
}

@model Services.Models.ListarPostsViewModelPaginated<Dominio.Post>
<!-- Page Header-->
<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            @foreach (var post in Model)
            {
                <!-- Post preview-->
                <div class="post-preview">
                    <a asp-action="visualizar" asp-controller="Post" asp-route-id="@post.Id">
                        <h2 class="post-title">@post.Titulo</h2>
                        <h3 class="post-subtitle">@post.Subtitulo</h3>
                    </a>
                    <p class="post-meta">
                        Posted by

                        on @String.Format("{0: dd/MM/yyyy hh:mm}", post.DataCriacao)
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
                <!-- Pager-->
            }
        </div>
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <a asp-action="Older"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           class="btn btn-default @prevDisabled">
            Anterior
        </a>
        <a asp-action="Older"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           class="btn btn-default @nextDisabled">
            Próximo
        </a>
    </div>
</div>

BlogApp/Views/Blog/Post.cshtml
@{
    Layout = "LayoutBlog";
}
<!-- Page Header-->
<header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>
                <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>
                <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>
                <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>
                <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>
                <h2 class="section-heading">The Final Frontier</h2>
                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>
                <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>
                <h2 class="section-heading">Reaching for the Stars</h2>
                <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>
                <a href="#!"><img class="img-fluid" src="assets/img/post-sample-image.jpg" alt="..." /></a>
                <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>
                <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
                <p>
                    Placeholder text by
                    <a href="http://spaceipsum.com/">Space Ipsum</a>
                    &middot; Images by
                    <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>
                </p>
            </div>
        </div>
    </div>
</article>